### ISSUE TITLE
App crashes when clicking 'Dump MessagePack' on lower Android versions.

### ISSUE THREAD

**Issue by EtherealAO** [Kimjio/umamusume-localify-android#19]
Tested devices: Pixel 2(8.1.0), Nox&LDPlayer (9)
logcat:
```
04-05 16:08:03.964  4903  4903 D AndroidRuntime: Shutting down VM
--------- beginning of crash
04-05 16:08:03.965  4903  4903 E AndroidRuntime: FATAL EXCEPTION: main
04-05 16:08:03.965  4903  4903 E AndroidRuntime: Process: com.kimjio.umamusumelocalify.settings, PID: 4903
04-05 16:08:03.965  4903  4903 E AndroidRuntime: android.view.InflateException: Binary XML file line #28: Binary XML file line #28: Error inflating class com.kimjio.umamusumelocalify.settings.widget.MainSwitchBar
04-05 16:08:03.965  4903  4903 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #28: Error inflating class com.kimjio.umamusumelocalify.settings.widget.MainSwitchBar
04-05 16:08:03.965  4903  4903 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at androidx.preference.d.g(PreferenceGroupAdapter.java:53)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$t.j(RecyclerView.java:841)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$t.d(RecyclerView.java:6)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager$c.b(LinearLayoutManager.java:54)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.U0(LinearLayoutManager.java:1)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.H0(LinearLayoutManager.java:54)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.a0(LinearLayoutManager.java:826)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.r(RecyclerView.java:79)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.p(RecyclerView.java:72)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:8)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at r2.h.u(HeaderScrollingViewBehavior.java:159)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at r2.i.h(ViewOffsetBehavior.java:1)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:41)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
04-05 16:08:03.965  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2799)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2316)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:696)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6737)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
04-05 16:08:03.966  4903  4903 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Drawable com.kimjio.umamusumelocalify.settings:drawable/settingslib_switch_bar_bg_on with resource ID #0x7f08010b
04-05 16:08:03.966  4903  4903 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/settingslib_switch_bar_bg_on.xml from drawable resource ID #0x7f08010b
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:857)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:641)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.content.res.Resources.getDrawableForDensity(Resources.java:888)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.content.res.Resources.getDrawable(Resources.java:827)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.content.Context.getDrawable(Context.java:635)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at v.a$b.b(ContextCompat.java:1)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at androidx.appcompat.widget.h1.f(ResourceManagerInternal.java:53)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at androidx.appcompat.widget.h1.e(ResourceManagerInternal.java:3)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at d.a.a(AppCompatResources.java:5)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at com.kimjio.umamusumelocalify.settings.widget.MainSwitchBar.<init>(MainSwitchBar.java:96)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at androidx.preference.d.g(PreferenceGroupAdapter.java:53)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$t.j(RecyclerView.java:841)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$t.d(RecyclerView.java:6)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager$c.b(LinearLayoutManager.java:54)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.U0(LinearLayoutManager.java:1)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.H0(LinearLayoutManager.java:54)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.a0(LinearLayoutManager.java:826)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.r(RecyclerView.java:79)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.p(RecyclerView.java:72)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:8)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at r2.h.u(HeaderScrollingViewBehavior.java:159)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at r2.i.h(ViewOffsetBehavior.java:1)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:41)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.View.layout(View.java:20686)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:6194)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2799)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2316)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:696)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6737)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
04-05 16:08:03.966  4903  4903 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Can't convert to ComplexColor: type=0x1
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1090)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:966)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1045)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.content.res.Resources.loadColorStateList(Resources.java:1041)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.content.res.TypedArray.getColorStateList(TypedArray.java:549)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.graphics.drawable.GradientDrawable.updateGradientDrawableSolid(GradientDrawable.java:1543)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.graphics.drawable.GradientDrawable.inflateChildElements(GradientDrawable.java:1427)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:1244)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1321)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:279)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:194)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.graphics.drawable.RippleDrawable.inflate(RippleDrawable.java:428)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:843)
04-05 16:08:03.966  4903  4903 E AndroidRuntime:        ... 86 more
04-05 16:08:03.968  4903  4946 E EGL_adreno: tid 4946: eglSurfaceAttrib(1338): error 0x3009 (EGL_BAD_MATCH)
04-05 16:08:03.968  4903  4946 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x7fff5a8bcc00, error=EGL_BAD_MATCH
```

**Comment by Kimjio** [comment]
Fixed on 1.5.2
